### ISSUE TITLE
Hintergrundkarte: MapQuest tiles sind nicht mehr frei nutzbar

### ISSUE THREAD

**Issue by chk1** [ifgi-webteam/Campusplan#27]
http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

https://lists.openstreetmap.org/pipermail/tile-serving/2016-June/003928.html

**Comment by nsteffens** [comment]
Habe daraufhin (in Anlehnung an GI@School) den Provider zu Mapbox geändert. Da diese ausdrücklich ein generelles serverseitiges Caching verbieten (vgl. [hier](https://www.mapbox.com/help/offline-map-cache/), habe ich den direkten mapbox-Link integriert. In den NGINX-Settings (welche nicht hier auf GitHub sind) habe ich ebenso eine Notiz angehangen.

Der Fehler ist damit behoben.
